spring:
  datasource:
    url: jdbc:mysql://175.24.234.14:3306/MyAdmin?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: ysw
    password: lingning48
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/*.xml  #sql映射文件位置